import {useState} from 'react'
import type {Loan} from './domain'
import type {Option} from '../../app/runtime'
const labels:Record<string,string>={requested:'Solicitado',approved:'Aprovado',rejected:'Rejeitado',released:'Liberado',completed:'Finalizado',cancelled:'Cancelado',in_use:'Em uso',return_pending:'Devolução pendente',availability_pending:'Aguardando confirmação'}
type LoanAction='approve'|'release'
export function LoansHome({loans,vehicles,canRequest,canApprove,canRelease,onNew,onCalendar,onAction}:{loans:Loan[];vehicles:Option[];canRequest:boolean;canApprove:boolean;canRelease:boolean;onNew:()=>void;onCalendar:()=>void;onAction:(id:string,action:LoanAction)=>Promise<void>}){
 const [busy,setBusy]=useState('');const [error,setError]=useState('')
 async function act(id:string,action:LoanAction){setBusy(id+action);setError('');try{await onAction(id,action)}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar a solicitação')}finally{setBusy('')}}
 const ordered=[...loans].sort((a,b)=>{const priority=(x:Loan)=>x.status==='approved'?0:x.status==='requested'?1:2;return priority(a)-priority(b)||b.period.start.localeCompare(a.period.start)})
 const awaitingRelease=loans.filter(x=>x.status==='approved').length
 return <section><div className="title-row"><h2>Solicitações</h2>{canRequest&&<button className="primary" onClick={onNew}>Nova solicitação</button>}</div>{canRelease&&<div className="notice warning"><strong>{awaitingRelease}</strong> veículo(s) aguardando liberação da Frota.</div>}<button className="secondary wide" onClick={onCalendar}>Abrir calendário de disponibilidade</button>{error&&<div className="notice error">{error}</div>}<div className="cards">{ordered.length?ordered.map(x=><article className="item" key={x.id}><strong>{vehicles.find(v=>v.id===x.vehicleId)?.label??'Veículo'}</strong><span>{x.destination}</span><span>{new Date(x.period.start).toLocaleString('pt-BR')}</span><em>{labels[x.status]??x.status.replaceAll('_',' ')}</em>{x.status==='requested'&&canApprove&&<div className="actions"><button className="primary" disabled={!!busy} onClick={()=>void act(x.id,'approve')}>{busy===x.id+'approve'?'Aprovando…':'Aprovar solicitação'}</button></div>}{x.status==='approved'&&canRelease&&<div className="actions"><button className="primary" disabled={!!busy} onClick={()=>void act(x.id,'release')}>{busy===x.id+'release'?'Liberando…':'Registrar saída / liberar'}</button></div>}</article>):<div className="empty">Nenhuma solicitação disponível para você.</div>}</div></section>
}
