import { useState,type FormEvent } from 'react'
type Option={id:string;label:string}
export function LoanRequestForm({online,vehicles,drivers,onSubmit}:{online:boolean;vehicles:Option[];drivers:Option[];onSubmit:(v:Record<string,string>)=>Promise<void>}){
 const [form,setForm]=useState({vehicleId:'',driverId:'',start:'',end:'',destination:'',purpose:''});const [sent,setSent]=useState(false);const [error,setError]=useState('');const [sending,setSending]=useState(false)
 const field=(key:keyof typeof form)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm({...form,[key]:e.target.value})
 async function submit(e:FormEvent){e.preventDefault();setError('');if(Date.parse(form.start)>=Date.parse(form.end)){setError('O retorno deve ser posterior ao início.');return}setSending(true);try{await onSubmit(form);setSent(true)}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar a solicitação.')}finally{setSending(false)}}
 if(sent)return <div className="notice warning">{online?'Solicitação enviada para confirmação':'Aguardando confirmação de disponibilidade'}</div>
 return <form className="form-card" onSubmit={submit}><h2>Solicitar veículo</h2>{error&&<div className="notice error">{error}</div>}<label>Veículo<select value={form.vehicleId} onChange={field('vehicleId')} required><option value="">Selecione</option>{vehicles.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>Motorista<select value={form.driverId} onChange={field('driverId')} required><option value="">Selecione</option>{drivers.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div className="two"><label>Início<input type="datetime-local" value={form.start} onChange={field('start')} required/></label><label>Retorno<input type="datetime-local" value={form.end} onChange={field('end')} required/></label></div><label>Destino<input value={form.destination} onChange={field('destination')} required/></label><label>Finalidade<input value={form.purpose} onChange={field('purpose')} required/></label><button className="primary" type="submit" disabled={sending}>{sending?'Enviando…':'Enviar solicitação'}</button>{!online&&<small>Você está offline. A reserva será confirmada ao sincronizar.</small>}</form>
}
