create schema if not exists private;

alter table public.usuarios
  add column if not exists mobile_permissions jsonb not null default '{}'::jsonb;

create table if not exists public.mobile_devices (
  id uuid primary key default gen_random_uuid(),
  tenant text not null,
  user_id uuid not null,
  name text,
  platform text,
  app_version text,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  unique (tenant, id)
);

create table if not exists public.mobile_operations (
  id bigint generated by default as identity primary key,
  tenant text not null,
  operation_id text not null,
  device_id uuid not null,
  user_id uuid not null,
  entity_type text not null,
  entity_id text not null,
  operation_kind text not null,
  base_version bigint,
  payload jsonb not null default '{}'::jsonb,
  result jsonb not null,
  device_created_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant, operation_id),
  foreign key (tenant, device_id) references public.mobile_devices(tenant, id)
);

create table if not exists public.mobile_audit_events (
  id bigint generated by default as identity primary key,
  tenant text not null,
  user_id uuid not null,
  device_id uuid,
  operation_id text,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  server_version bigint not null default 1,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.mobile_attachments (
  id uuid primary key default gen_random_uuid(),
  tenant text not null,
  user_id uuid not null,
  device_id uuid not null,
  entity_type text not null,
  entity_id text not null,
  storage_path text not null,
  mime_type text,
  size_bytes bigint,
  sha256 text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tenant, storage_path),
  foreign key (tenant, device_id) references public.mobile_devices(tenant, id)
);

create index if not exists mobile_devices_user_idx
  on public.mobile_devices (tenant, user_id, enabled);
create index if not exists mobile_operations_sync_idx
  on public.mobile_operations (tenant, updated_at, id);
create index if not exists mobile_operations_user_idx
  on public.mobile_operations (tenant, user_id, created_at desc);
create index if not exists mobile_audit_events_sync_idx
  on public.mobile_audit_events (tenant, created_at, id);
create index if not exists mobile_attachments_sync_idx
  on public.mobile_attachments (tenant, updated_at, id);

alter table public.mobile_devices enable row level security;
alter table public.mobile_operations enable row level security;
alter table public.mobile_audit_events enable row level security;
alter table public.mobile_attachments enable row level security;

revoke all on public.mobile_devices from anon, authenticated;
revoke all on public.mobile_operations from anon, authenticated;
revoke all on public.mobile_audit_events from anon, authenticated;
revoke all on public.mobile_attachments from anon, authenticated;
grant select, insert, update on public.mobile_devices to authenticated;
grant select on public.mobile_operations to authenticated;
grant select on public.mobile_audit_events to authenticated;
grant select, insert, update on public.mobile_attachments to authenticated;

drop policy if exists mobile_devices_own on public.mobile_devices;
create policy mobile_devices_own on public.mobile_devices
  for all to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and tenant = public.fm_user_tenant()
    and exists (
      select 1 from public.usuarios u
      where u.auth_user_id = auth.uid()
        and u.tenant = mobile_devices.tenant
        and coalesce(u.ativo, true)
        and not coalesce(u.excluido, false)
        and not coalesce(u.pendente_aprovacao, false)
        and coalesce((u.mobile_permissions ->> 'mobile.access')::boolean, false)
    )
  );

drop policy if exists mobile_operations_own on public.mobile_operations;
create policy mobile_operations_own on public.mobile_operations
  for select to authenticated
  using (user_id = auth.uid() and tenant = public.fm_user_tenant());

drop policy if exists mobile_audit_events_tenant on public.mobile_audit_events;
create policy mobile_audit_events_tenant on public.mobile_audit_events
  for select to authenticated
  using (tenant = public.fm_user_tenant());

drop policy if exists mobile_attachments_own on public.mobile_attachments;
create policy mobile_attachments_own on public.mobile_attachments
  for all to authenticated
  using (user_id = auth.uid() and tenant = public.fm_user_tenant())
  with check (
    user_id = auth.uid()
    and tenant = public.fm_user_tenant()
    and exists (
      select 1 from public.mobile_devices d
      where d.id = mobile_attachments.device_id
        and d.tenant = mobile_attachments.tenant
        and d.user_id = auth.uid()
        and d.enabled
    )
  );

create or replace function private.mobile_text_ids(value text)
returns jsonb
language plpgsql
immutable
set search_path = pg_catalog
as $$
declare parsed jsonb;
begin
  if value is null or btrim(value) = '' then return '[]'::jsonb; end if;
  begin
    parsed := value::jsonb;
    if jsonb_typeof(parsed) = 'array' then return parsed; end if;
  exception when others then
    null;
  end;
  return to_jsonb(regexp_split_to_array(regexp_replace(value, '[\\[\\]" ]', '', 'g'), ','));
end;
$$;

create or replace function public.get_mobile_scope()
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  profile public.usuarios%rowtype;
  company_ids jsonb;
  vehicle_ids jsonb;
  sector_ids jsonb;
  driver_ids jsonb;
  permissions jsonb;
begin
  if auth.uid() is null then raise insufficient_privilege using message = 'Autenticação obrigatória'; end if;

  select * into profile
  from public.usuarios
  where auth_user_id = auth.uid()
    and coalesce(ativo, true)
    and not coalesce(excluido, false)
    and not coalesce(pendente_aprovacao, false)
  order by id
  limit 1;

  if not found then raise insufficient_privilege using message = 'Usuário inativo ou sem perfil'; end if;
  if not coalesce((profile.mobile_permissions ->> 'mobile.access')::boolean, false) then
    raise insufficient_privilege using message = 'Acesso ao aplicativo não liberado';
  end if;

  company_ids := private.mobile_text_ids(profile.empresas);
  sector_ids := case when profile.setor_id is null then '[]'::jsonb else jsonb_build_array(profile.setor_id::text) end;
  vehicle_ids := coalesce(profile.equipamentos_vinculados, '[]'::jsonb);

  select coalesce(jsonb_agg(m.id::text order by m.id), '[]'::jsonb)
    into driver_ids
  from public.motoristas m
  where m.tenant = profile.tenant
    and not coalesce(m.excluido, false)
    and (profile.setor_id is null or m.setor_id = profile.setor_id);

  select coalesce(jsonb_agg(key order by key), '[]'::jsonb)
    into permissions
  from jsonb_each(profile.mobile_permissions)
  where jsonb_typeof(value) = 'boolean' and value = 'true'::jsonb;

  return jsonb_build_object(
    'tenant', profile.tenant,
    'userId', auth.uid()::text,
    'companyIds', company_ids,
    'sectorIds', sector_ids,
    'vehicleIds', vehicle_ids,
    'driverIds', driver_ids,
    'permissions', permissions,
    'validatedAt', to_char(clock_timestamp() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    'expiresAt', to_char((clock_timestamp() + interval '7 days') at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
  );
end;
$$;

create or replace function public.process_mobile_operation(p_device_id uuid, p_operation jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, private
as $$
declare
  profile public.usuarios%rowtype;
  v_operation_id text := nullif(p_operation ->> 'operationId', '');
  entity_type text := nullif(p_operation ->> 'entityType', '');
  entity_id text := nullif(p_operation ->> 'entityId', '');
  operation_kind text := nullif(p_operation ->> 'kind', '');
  required_permission text;
  stored_result jsonb;
begin
  if auth.uid() is null then raise insufficient_privilege using message = 'Autenticação obrigatória'; end if;
  if v_operation_id is null or entity_type is null or entity_id is null or operation_kind is null then
    raise invalid_parameter_value using message = 'Operação incompleta';
  end if;

  select * into profile from public.usuarios
  where auth_user_id = auth.uid()
    and coalesce(ativo, true)
    and not coalesce(excluido, false)
    and not coalesce(pendente_aprovacao, false)
  order by id limit 1;
  if not found then raise insufficient_privilege using message = 'Usuário inativo ou sem perfil'; end if;
  if not coalesce((profile.mobile_permissions ->> 'mobile.access')::boolean, false) then
    raise insufficient_privilege using message = 'Acesso ao aplicativo não liberado';
  end if;

  if not exists (
    select 1 from public.mobile_devices d
    where d.id = p_device_id and d.tenant = profile.tenant and d.user_id = auth.uid() and d.enabled
  ) then raise insufficient_privilege using message = 'Dispositivo não autorizado'; end if;

  select result into stored_result from public.mobile_operations
  where tenant = profile.tenant and operation_id = v_operation_id;
  if found then return stored_result || jsonb_build_object('outcome', 'duplicate'); end if;

  required_permission := case entity_type
    when 'loan' then case when operation_kind = 'create' then 'loan.request' else 'loan.view' end
    when 'loan_checklist' then 'loan.checklist'
    when 'work_order' then case when operation_kind = 'create' then 'work_order.create' else 'work_order.execute' end
    when 'work_order_entry' then 'work_order.execute'
    when 'attachment' then case when p_operation -> 'payload' ->> 'parentType' like 'loan%' then 'loan.checklist' else 'work_order.execute' end
    else null
  end;

  if required_permission is null or not coalesce((profile.mobile_permissions ->> required_permission)::boolean, false) then
    stored_result := jsonb_build_object('operationId', v_operation_id, 'outcome', 'rejected', 'code', 'PERMISSION_DENIED', 'message', 'Operação não autorizada');
  else
    stored_result := jsonb_build_object('operationId', v_operation_id, 'outcome', 'rejected', 'code', 'HANDLER_NOT_INSTALLED', 'message', 'Módulo ainda não publicado no servidor');
  end if;

  insert into public.mobile_operations (
    tenant, operation_id, device_id, user_id, entity_type, entity_id,
    operation_kind, base_version, payload, result, device_created_at
  ) values (
    profile.tenant, v_operation_id, p_device_id, auth.uid(), entity_type, entity_id,
    operation_kind, nullif(p_operation ->> 'baseVersion', '')::bigint,
    coalesce(p_operation -> 'payload', '{}'::jsonb), stored_result,
    nullif(p_operation ->> 'deviceCreatedAt', '')::timestamptz
  ) on conflict (tenant, operation_id) do nothing;

  update public.mobile_devices set last_seen_at = now() where id = p_device_id;
  return stored_result;
end;
$$;

revoke all on function public.get_mobile_scope() from public, anon;
revoke all on function public.process_mobile_operation(uuid, jsonb) from public, anon;
grant execute on function public.get_mobile_scope() to authenticated;
grant execute on function public.process_mobile_operation(uuid, jsonb) to authenticated;
